spring:
  config:
    activate:
      on-profile: loc

  datasource:
    url: jdbc:postgresql://localhost:5435/platformdb
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

platform:
  image-service:
    url: http://localhost:8200

server:
  port: 8081

logging:
  level:
    com.lagu.platform: DEBUG
    org.springframework.kafka: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
