spring:
  config:
    activate:
      on-profile: loc

  datasource:
    url: jdbc:postgresql://localhost:5435/platformdb
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

  mail:
    host: localhost
    port: 1025

platform:
  notification:
    email:
      enabled: false
      from: noreply@lagu.platform
      dry-run: true

server:
  port: 8084

logging:
  level:
    com.lagu.platform: DEBUG
    org.springframework.kafka: INFO
    org.springframework.mail: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
